from __future__ import annotations

from src.application.strategy_lab.contracts import (
    BACKTEST_CONCLUSIONS,
    BLOCKED_STANDARD_RATIO_METRICS,
    CORE_METRIC_NAMES,
    BacktestResult,
    CandidateSnapshot,
    EvidenceArtifact,
    EvidenceRef,
    MetricSet,
    StrategyExperiment,
    StrategyLabEvidence,
    StrategyPolicy,
    validate_metric_names,
    validate_strategy_type,
)
from src.application.strategy_lab.evidence_loader import load_strategy_lab_evidence
from src.application.strategy_lab.historical_data import (
    FutuHistoricalFetchOptions,
    FutuHistoricalMarketDataProvider,
    HISTORICAL_DATA_SCHEMA_VERSION,
    HistoricalBar,
    HistoricalDataCache,
    HistoricalDataRequest,
    HistoricalDataSnapshot,
    HistoricalMarketDataProvider,
    build_historical_data_snapshot,
    fetch_historical_data_tool,
    historical_snapshot_summary,
    load_historical_data_snapshots,
    normalize_historical_symbols,
)
from src.application.strategy_lab.report import (
    StrategyLabReport,
    build_strategy_lab_report,
    render_strategy_lab_markdown,
)
from src.application.strategy_lab.service import strategy_lab_tool
from src.application.strategy_lab.simulator import run_replay_backtest

__all__ = [
    "BACKTEST_CONCLUSIONS",
    "BLOCKED_STANDARD_RATIO_METRICS",
    "CORE_METRIC_NAMES",
    "FutuHistoricalFetchOptions",
    "FutuHistoricalMarketDataProvider",
    "HISTORICAL_DATA_SCHEMA_VERSION",
    "BacktestResult",
    "CandidateSnapshot",
    "EvidenceArtifact",
    "EvidenceRef",
    "HistoricalBar",
    "HistoricalDataCache",
    "HistoricalDataRequest",
    "HistoricalDataSnapshot",
    "HistoricalMarketDataProvider",
    "MetricSet",
    "StrategyExperiment",
    "StrategyLabReport",
    "StrategyLabEvidence",
    "StrategyPolicy",
    "build_strategy_lab_report",
    "build_historical_data_snapshot",
    "fetch_historical_data_tool",
    "historical_snapshot_summary",
    "load_historical_data_snapshots",
    "load_strategy_lab_evidence",
    "normalize_historical_symbols",
    "render_strategy_lab_markdown",
    "run_replay_backtest",
    "strategy_lab_tool",
    "validate_metric_names",
    "validate_strategy_type",
]
